# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 06:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='favorMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicName', models.CharField(max_length=30, verbose_name='歌曲名')),
                ('covers', models.ImageField(default='static/ailb/essay/default.png', upload_to='ailb/favormusic/%Y/%m', verbose_name='唱片封面')),
                ('singer', models.CharField(max_length=30, verbose_name='歌手名')),
                ('album', models.CharField(max_length=30, verbose_name='专集名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '收藏歌曲表',
                'verbose_name_plural': '收藏歌曲表',
                'db_table': 'tb_favormusic',
            },
        ),
        migrations.CreateModel(
            name='replyEssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replyDetail', models.CharField(max_length=1000, verbose_name='回复内容')),
                ('replyDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='回复日期')),
            ],
            options={
                'verbose_name': '文章回复信息表',
                'verbose_name_plural': '文章回复信息表',
                'db_table': 'tb_replyessay',
            },
        ),
        migrations.CreateModel(
            name='TechEssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essayTitle', models.CharField(max_length=30, verbose_name='文章标题')),
                ('essayContext', models.TextField(verbose_name='文章内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加日期')),
                ('image', models.ImageField(default='static/ailb/essay/default.png', upload_to='ailb/essay/%Y/%m', verbose_name='文章图片')),
                ('favor', models.IntegerField(verbose_name='点赞数')),
                ('viewNum', models.IntegerField(verbose_name='被查看数')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
            ],
            options={
                'verbose_name': '技术文章表',
                'verbose_name_plural': '技术文章表',
                'db_table': 'tb_techessay',
            },
        ),
        migrations.AddField(
            model_name='replyessay',
            name='techEssay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ailb.TechEssay'),
        ),
    ]
